/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SolucaoSistemasVIEW;

import SolucaoSistemasCTR.AgendamentoCTR;
import SolucaoSistemasCTR.PessoaCTR;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Vinicius
 */
public class AgendamentoVIEW extends javax.swing.JDialog {

    DateFormat dataFormatar = new SimpleDateFormat("yyyy-MM-dd");
    AgendamentoCTR objagendaCTR = new AgendamentoCTR();
    String situacao = "";
    public static String codigoAnimal = "";
    ResultSet persona = null;
    PessoaCTR objpessoaCTR = new PessoaCTR();

    /**
     * Creates new form AgendamentoVIEW
     */
    public AgendamentoVIEW(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("AGENDA");
        this.setLocationRelativeTo(null);
        UtilVIEW.Icone(this);
        UtilVIEW.DataAtual(txtData);
        if (PesquisaAgendamentoVIEW.codigoAgenda.equals("")) {
            rbDisponivel.setSelected(true);
        } else {
            RestaurarAgenda();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GruposAgendamento = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtAgendar = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        txtHora = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDiaSemana = new javax.swing.JTextField();
        rbDisponivel = new javax.swing.JCheckBox();
        rbConfirmado = new javax.swing.JCheckBox();
        rbAConfirmar = new javax.swing.JCheckBox();
        rbCancelado = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        btnPesquisaCliente = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTelefone1 = new javax.swing.JTextField();
        txtTelefone2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNomeAnimal = new javax.swing.JTextField();
        btnPesquisaAnimal = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cbxAtendente = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        cbxVeterinario = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacao = new javax.swing.JTextPane();
        btnGeraAtendimento = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtNumeroAtendimento = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtData = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Data Agendamento:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 31, 130, 15);

        txtAgendar.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.add(txtAgendar);
        txtAgendar.setBounds(10, 50, 120, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Hora:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(140, 31, 70, 15);

        txtHora.setBackground(new java.awt.Color(255, 255, 204));
        try {
            txtHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtHora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHoraKeyPressed(evt);
            }
        });
        jPanel1.add(txtHora);
        txtHora.setBounds(140, 50, 60, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Dia da Semana:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(210, 31, 130, 15);

        txtDiaSemana.setBackground(new java.awt.Color(255, 255, 204));
        txtDiaSemana.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDiaSemanaKeyPressed(evt);
            }
        });
        jPanel1.add(txtDiaSemana);
        txtDiaSemana.setBounds(210, 50, 100, 20);

        GruposAgendamento.add(rbDisponivel);
        rbDisponivel.setText("Horário Disponível");
        jPanel1.add(rbDisponivel);
        rbDisponivel.setBounds(320, 10, 130, 23);

        GruposAgendamento.add(rbConfirmado);
        rbConfirmado.setText("Horário Confirmado");
        jPanel1.add(rbConfirmado);
        rbConfirmado.setBounds(320, 30, 140, 23);

        GruposAgendamento.add(rbAConfirmar);
        rbAConfirmar.setText("Horário A Confirmar");
        jPanel1.add(rbAConfirmar);
        rbAConfirmar.setBounds(320, 50, 140, 23);

        GruposAgendamento.add(rbCancelado);
        rbCancelado.setText("Horário Cancelado");
        jPanel1.add(rbCancelado);
        rbCancelado.setBounds(320, 70, 140, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(4, 4, 470, 100);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(null);

        jLabel4.setText("Nome do Cliente/Dono:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 13, 163, 14);

        txtCliente.setEditable(false);
        txtCliente.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.add(txtCliente);
        txtCliente.setBounds(10, 30, 300, 20);

        btnPesquisaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Lupa_32x32.png"))); // NOI18N
        btnPesquisaCliente.setText("Pesquisar Cliente");
        btnPesquisaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaClienteActionPerformed(evt);
            }
        });
        jPanel2.add(btnPesquisaCliente);
        btnPesquisaCliente.setBounds(316, 12, 150, 40);

        jLabel5.setText("Telefone 1:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 60, 70, 14);

        jLabel6.setText("Telefone 2:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(120, 60, 80, 14);

        txtTelefone1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelefone1KeyPressed(evt);
            }
        });
        jPanel2.add(txtTelefone1);
        txtTelefone1.setBounds(10, 80, 100, 20);

        txtTelefone2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelefone2KeyPressed(evt);
            }
        });
        jPanel2.add(txtTelefone2);
        txtTelefone2.setBounds(120, 80, 100, 20);

        jLabel7.setText("Nome do Animal:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 110, 140, 14);

        txtNomeAnimal.setEditable(false);
        txtNomeAnimal.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.add(txtNomeAnimal);
        txtNomeAnimal.setBounds(10, 130, 300, 20);

        btnPesquisaAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/patas.JPG"))); // NOI18N
        btnPesquisaAnimal.setText("Pesquisar Animal");
        btnPesquisaAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaAnimalActionPerformed(evt);
            }
        });
        jPanel2.add(btnPesquisaAnimal);
        btnPesquisaAnimal.setBounds(316, 113, 150, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(4, 110, 470, 160);

        jLabel8.setText("Atendente:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 280, 80, 14);

        cbxAtendente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        cbxAtendente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbxAtendenteFocusGained(evt);
            }
        });
        cbxAtendente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbxAtendenteKeyPressed(evt);
            }
        });
        getContentPane().add(cbxAtendente);
        cbxAtendente.setBounds(10, 300, 210, 20);

        jLabel9.setText("Veterinário:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(230, 280, 120, 14);

        cbxVeterinario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        cbxVeterinario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbxVeterinarioFocusGained(evt);
            }
        });
        cbxVeterinario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbxVeterinarioKeyPressed(evt);
            }
        });
        getContentPane().add(cbxVeterinario);
        cbxVeterinario.setBounds(230, 300, 210, 20);

        jScrollPane1.setViewportView(txtObservacao);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 330, 460, 70);

        btnGeraAtendimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/atendimentoPequeno.JPG"))); // NOI18N
        btnGeraAtendimento.setText("Gerar Atendimento");
        btnGeraAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeraAtendimentoActionPerformed(evt);
            }
        });
        getContentPane().add(btnGeraAtendimento);
        btnGeraAtendimento.setBounds(10, 410, 160, 40);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/sair_32x32.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(180, 410, 130, 40);

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/7881_32x32.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(320, 410, 130, 40);

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Imprimir_32x32.png"))); // NOI18N
        btnImprimir.setText("Imprimir");
        getContentPane().add(btnImprimir);
        btnImprimir.setBounds(180, 460, 130, 40);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/casa_32x32.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(320, 460, 130, 40);

        jLabel10.setText("Nº Atendimento:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 460, 90, 14);

        txtNumeroAtendimento.setEditable(false);
        getContentPane().add(txtNumeroAtendimento);
        txtNumeroAtendimento.setBounds(10, 480, 80, 20);

        jLabel11.setText("Data:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(100, 460, 27, 14);
        getContentPane().add(txtData);
        txtData.setBounds(100, 480, 70, 20);

        setBounds(0, 0, 495, 546);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            if (rbDisponivel.isSelected() == true) {
                situacao = "DISPONIVEL";
            } else if (rbConfirmado.isSelected() == true) {
                situacao = "CONFIRMADO";
            } else if (rbAConfirmar.isSelected() == true) {
                situacao = "CONFIRMAR";
            } else if (rbCancelado.isSelected() == true) {
                situacao = "CANCELADO";
            }
            if (PesquisaAgendamentoVIEW.codigoAgenda.equals("")) {
                CadastrarAgendaVIEW();
            } else {
                AlterarAgendaVIEW();
            }
            this.dispose();
            new PesquisaAgendamentoVIEW(null, true).setVisible(true);
        } catch (Exception e) {
            System.out.println("Botão Salvar " + e.getMessage());
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnGeraAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeraAtendimentoActionPerformed
        this.dispose();
        new AtendimentoVIEW(null, true).setVisible(true);
    }//GEN-LAST:event_btnGeraAtendimentoActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        try {
            int sair = -1;
            sair = JOptionPane.showConfirmDialog(null, "Deseja sair?", "PERGUNTA",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (sair == 0) {
                this.dispose();
            } else if (sair == 1) {

            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btnSairActionPerformed
    public static boolean agendarCliente = false;
    private void btnPesquisaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaClienteActionPerformed
        agendarCliente = true;
        new PesquisaDiversosVIEW(null, true).setVisible(true);
    }//GEN-LAST:event_btnPesquisaClienteActionPerformed
    public static boolean agendarAnimal = false;
    private void btnPesquisaAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaAnimalActionPerformed
        codigoAnimal = "";
        agendarAnimal = true;
        new PesquisaAnimaisVIEW(null, true).setVisible(true);
    }//GEN-LAST:event_btnPesquisaAnimalActionPerformed

    private void cbxAtendenteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxAtendenteFocusGained
        try {

            persona = objpessoaCTR.ConsultarPessoaCTR("0", "", "FUNCIONARIO", "FUNCIONARIO");
            UtilVIEW.PreencheCombo(persona, cbxAtendente, 2);
            persona = null;
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cbxAtendenteFocusGained

    private void cbxVeterinarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxVeterinarioFocusGained
        try {

            persona = objpessoaCTR.ConsultarPessoaCTR("0", "", "VETERINARIO", "VETERINARIO");
            UtilVIEW.PreencheCombo(persona, cbxVeterinario, 2);
            persona = null;
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cbxVeterinarioFocusGained

    private void txtHoraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHoraKeyPressed
        try {
            if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
                txtDiaSemana.requestFocusInWindow();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtHoraKeyPressed

    private void txtDiaSemanaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiaSemanaKeyPressed
        try {
            if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
                btnPesquisaCliente.requestFocusInWindow();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtDiaSemanaKeyPressed

    private void txtTelefone1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefone1KeyPressed
        try {
            if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
                txtTelefone2.requestFocusInWindow();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtTelefone1KeyPressed

    private void txtTelefone2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefone2KeyPressed
        try {
            if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
                btnPesquisaAnimal.requestFocusInWindow();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtTelefone2KeyPressed

    private void cbxAtendenteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbxAtendenteKeyPressed
        try {
            if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
                cbxVeterinario.requestFocusInWindow();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cbxAtendenteKeyPressed

    private void cbxVeterinarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbxVeterinarioKeyPressed
        try {
            if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
                txtObservacao.requestFocusInWindow();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cbxVeterinarioKeyPressed

    private void CadastrarAgendaVIEW() {
        try {
            if (codigoAnimal.equals("")) {
                codigoAnimal = "0";
            } else {

            }
            if (objagendaCTR.CadastrarAgendaCTR(dataFormatar.format(txtAgendar.getDate()),
                    txtHora.getText(), txtDiaSemana.getText(), situacao,
                    txtCliente.getText(), codigoAnimal, txtTelefone1.getText(), txtTelefone2.getText(),
                    String.valueOf(cbxAtendente.getSelectedItem()),
                    String.valueOf(cbxVeterinario.getSelectedItem()),
                    txtObservacao.getText().toUpperCase())) {
                JOptionPane.showMessageDialog(null, "Salvo com sucesso!", "MENSAGEM",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao salvar", "MENSAGEM",
                    JOptionPane.WARNING_MESSAGE);
        }
    }

    private void AlterarAgendaVIEW() {
        try {

            if (objagendaCTR.AlterarAgendaCTR(dataFormatar.format(txtAgendar.getDate()),
                    txtHora.getText(), txtDiaSemana.getText(), situacao,
                    txtCliente.getText(), codigoAnimal, txtTelefone1.getText(), txtTelefone2.getText(),
                    String.valueOf(cbxAtendente.getSelectedItem()),
                    String.valueOf(cbxVeterinario.getSelectedItem()),
                    txtObservacao.getText().toUpperCase(), PesquisaAgendamentoVIEW.codigoAgenda)) {
                JOptionPane.showMessageDialog(null, "Agendado com sucesso!", "MENSAGEM",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao agendar", "MENSAGEM",
                    JOptionPane.WARNING_MESSAGE);
        }
    }

    private void RestaurarAgenda() {
        try {
            ResultSet restaura = null;
            restaura = objagendaCTR.ConsultarAgendaCTR(PesquisaAgendamentoVIEW.codigoAgenda);
            if (restaura.next()) {
                txtAgendar.setDate(restaura.getDate("datas"));
                txtHora.setText(restaura.getString("hora"));
                txtDiaSemana.setText(restaura.getString("dia"));
                txtCliente.setText(restaura.getString("cliente"));
                txtNomeAnimal.setText(restaura.getString("nome"));
                codigoAnimal = restaura.getString("animal");
                txtTelefone1.setText(restaura.getString("telefone1"));
                txtTelefone2.setText(restaura.getString("telefone2"));
                cbxAtendente.removeAllItems();
                cbxAtendente.addItem(restaura.getString("atendente"));
                cbxVeterinario.removeAllItems();
                cbxVeterinario.addItem(restaura.getString("veterinario"));
                txtObservacao.setText(restaura.getString("observacao"));
                if (restaura.getString("situacao").equals("DISPONIVEL")) {
                    rbDisponivel.setSelected(true);
                } else if (restaura.getString("situacao").equals("CONFIRMADO")) {
                    rbConfirmado.setSelected(true);
                } else if (restaura.getString("situacao").equals("CONFIRMAR")) {
                    rbAConfirmar.setSelected(true);
                } else if (restaura.getString("situacao").equals("CANCELADO")) {
                    rbCancelado.setSelected(true);
                }
            }
        } catch (Exception e) {
            System.out.println("" + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendamentoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendamentoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendamentoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendamentoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                AgendamentoVIEW dialog = new AgendamentoVIEW(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GruposAgendamento;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGeraAtendimento;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnPesquisaAnimal;
    private javax.swing.JButton btnPesquisaCliente;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    public static javax.swing.JComboBox cbxAtendente;
    private javax.swing.JComboBox cbxVeterinario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox rbAConfirmar;
    private javax.swing.JCheckBox rbCancelado;
    private javax.swing.JCheckBox rbConfirmado;
    private javax.swing.JCheckBox rbDisponivel;
    private com.toedter.calendar.JDateChooser txtAgendar;
    public static javax.swing.JTextField txtCliente;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JTextField txtDiaSemana;
    private javax.swing.JFormattedTextField txtHora;
    public static javax.swing.JTextField txtNomeAnimal;
    private javax.swing.JTextField txtNumeroAtendimento;
    private javax.swing.JTextPane txtObservacao;
    public static javax.swing.JTextField txtTelefone1;
    private javax.swing.JTextField txtTelefone2;
    // End of variables declaration//GEN-END:variables
}
