/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SolucaoSistemasVIEW;

import SolucaoSistemasDAO.ConectaBanco;
import java.awt.HeadlessException;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Batman
 */
public class BalancoFinanceiro extends javax.swing.JDialog {

    /**
     * Creates new form BalancoFinanceiro
     */
    public BalancoFinanceiro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        UtilVIEW.Icone(this);
        this.setTitle("BALANÇO FINANCEIRO");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoRelatorio = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        rbValores = new javax.swing.JCheckBox();
        rbBarras = new javax.swing.JCheckBox();
        rbPizza = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnVisualizar = new javax.swing.JButton();
        txtDataInicial = new com.toedter.calendar.JDateChooser();
        txtDataFinal = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Configurações Relatório:"));
        jPanel2.setLayout(null);

        grupoRelatorio.add(rbValores);
        rbValores.setText("Valores");
        rbValores.setOpaque(false);
        jPanel2.add(rbValores);
        rbValores.setBounds(6, 14, 61, 23);

        grupoRelatorio.add(rbBarras);
        rbBarras.setText("Barras");
        rbBarras.setOpaque(false);
        jPanel2.add(rbBarras);
        rbBarras.setBounds(69, 14, 57, 23);

        grupoRelatorio.add(rbPizza);
        rbPizza.setText("Pizza");
        jPanel2.add(rbPizza);
        rbPizza.setBounds(128, 14, 49, 23);

        jLabel1.setText("Data Inicial:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 36, 57, 14);

        jLabel2.setText("Data Final:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(104, 36, 59, 14);

        btnVisualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Imprimir_32x32.png"))); // NOI18N
        btnVisualizar.setText("Visualizar");
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btnVisualizar);
        btnVisualizar.setBounds(10, 80, 180, 40);
        jPanel2.add(txtDataInicial);
        txtDataInicial.setBounds(10, 55, 87, 20);
        jPanel2.add(txtDataFinal);
        txtDataFinal.setBounds(104, 55, 87, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setBounds(0, 0, 217, 169);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
        ImprimirBalancoFinanceiro();
    }//GEN-LAST:event_btnVisualizarActionPerformed

    private void ImprimirBalancoFinanceiro() {
        try {
            if (txtDataInicial.getDate() == null || txtDataFinal.getDate() == null) {
                JOptionPane.showMessageDialog(null, "Informar as datas!", "ATENÇÃO",
                        JOptionPane.WARNING_MESSAGE);
            } else {

                int op = -1;
                op = JOptionPane.showConfirmDialog(null, "Impressora esta ligada?", "PERGUNTA",
                        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (op == 0) {
                    this.dispose();
                    URL arquivo = null;
                    if (rbValores.isSelected() == true) {
                        PrincipalVIEW.relBalanco = true;
                        arquivo = getClass().getResource("/Relatorios/BalancoFinanceiro.jasper");
                    } else if (rbBarras.isSelected() == true) {
                        PrincipalVIEW.relBalanco = false;
                        arquivo = getClass().getResource("/Relatorios/GraficoBarras.jasper");
                    } else if (rbPizza.isSelected() == true) {
                        PrincipalVIEW.relBalanco = false;
                        arquivo = getClass().getResource("/Relatorios/GraficoPizza.jasper");
                    }

                    //JOptionPane.showMessageDialog(this, arquivo.toString());
                    if (arquivo == null) {
                        System.out.println("ARQUIVO INEXISTENTE");
                    } else {

                        ConectaBanco.ConectaPostgres();
                        JasperPrint rel = null;
                        Map parametros = new HashMap();
                        if (PrincipalVIEW.relBalanco == true) {
                            parametros.put("dataBR1", new SimpleDateFormat("dd/MM/yyyy").format(txtDataInicial.getDate()));
                            parametros.put("dataBR2", new SimpleDateFormat("dd/MM/yyyy").format(txtDataFinal.getDate()));
                        }

                        parametros.put("dataInicial", new SimpleDateFormat("yyyy-MM-dd").format(txtDataInicial.getDate()));
                        parametros.put("dataFinal", new SimpleDateFormat("yyyy-MM-dd").format(txtDataFinal.getDate()));

                        JasperReport jr;
                        try {
                            jr = (JasperReport) JRLoader.loadObject(arquivo);
                            rel = JasperFillManager.fillReport(jr, parametros, ConectaBanco.con);
                            JasperViewer.viewReport(rel, false);
                        } catch (JRException ex) {
                            System.out.println("" + ex.getMessage());
                        }

                    }
                    
                    PrincipalVIEW.relBalanco = false;
                    
                } else if (op == 1) {

                }

            }
        } catch (HeadlessException | NumberFormatException e) {
            System.out.println("" + e.getMessage());
        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BalancoFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BalancoFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BalancoFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BalancoFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                BalancoFinanceiro dialog = new BalancoFinanceiro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVisualizar;
    private javax.swing.ButtonGroup grupoRelatorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBox rbBarras;
    private javax.swing.JCheckBox rbPizza;
    private javax.swing.JCheckBox rbValores;
    private com.toedter.calendar.JDateChooser txtDataFinal;
    private com.toedter.calendar.JDateChooser txtDataInicial;
    // End of variables declaration//GEN-END:variables
}
