/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SolucaoSistemasVIEW;

import SolucaoSistemasCTR.ConfiguracaoRelatorioCTR;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Vinicius
 */
public class ConfiguracaoVIEW extends javax.swing.JDialog {

    ConfiguracaoRelatorioCTR objconfigurarCTR = new ConfiguracaoRelatorioCTR();
    /**
     * Creates new form ConfiguracaoVIEW
     */
    public ConfiguracaoVIEW(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        UtilVIEW.Icone(this);
        this.setLocationRelativeTo(null);
        this.setTitle("Configurar Relatório");
        try {
            ConsultarLogo();
        } catch (Exception e) {
            System.out.println("Formulario "+e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRelatorio = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNomeFantasia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        txtTelefone1 = new javax.swing.JTextField();
        txtTelefone2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        lblRelatorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRelatorio.setText("FOTO");
        getContentPane().add(lblRelatorio);
        lblRelatorio.setBounds(10, 10, 160, 150);

        jButton1.setText("Pesquisar Foto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 170, 160, 23);

        jLabel2.setText("Nome Fantasia:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 10, 120, 14);

        txtNomeFantasia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeFantasiaKeyPressed(evt);
            }
        });
        getContentPane().add(txtNomeFantasia);
        txtNomeFantasia.setBounds(190, 30, 370, 20);

        jLabel3.setText("Telefone 1:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 60, 100, 14);

        jLabel4.setText("Telefone 2:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 60, 120, 14);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(190, 110, 110, 23);

        btnSair.setText("Alterar");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(310, 110, 90, 23);

        txtTelefone1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelefone1KeyPressed(evt);
            }
        });
        getContentPane().add(txtTelefone1);
        txtTelefone1.setBounds(190, 80, 100, 20);
        getContentPane().add(txtTelefone2);
        txtTelefone2.setBounds(300, 80, 100, 20);

        setBounds(0, 0, 583, 245);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        UtilVIEW.Imagem(lblRelatorio);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(txtNomeFantasia.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Preencher os campos!", 
                    "MENSAGEM", JOptionPane.WARNING_MESSAGE);
        }else{
            SalvarConfiguracao();
            this.dispose();
        }
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        if(txtNomeFantasia.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Preencher os campos!", 
                    "MENSAGEM", JOptionPane.WARNING_MESSAGE);
            txtNomeFantasia.requestFocusInWindow();
        }else{
            if(lblRelatorio.getText().equals("")){
                
            }else{
                AlterarImagemRelatorio();
            }
            AtualizarConfiguracao();
            this.dispose();
        }
    }//GEN-LAST:event_btnSairActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        txtNomeFantasia.requestFocusInWindow();
    }//GEN-LAST:event_formWindowOpened

    private void txtNomeFantasiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeFantasiaKeyPressed
        if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            txtTelefone1.requestFocusInWindow();
        }
    }//GEN-LAST:event_txtNomeFantasiaKeyPressed

    private void txtTelefone1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefone1KeyPressed
        if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            txtTelefone2.requestFocusInWindow();
        }
    }//GEN-LAST:event_txtTelefone1KeyPressed

    private void ConsultarLogo(){
        try {
            ResultSet logo = null;
            logo = objconfigurarCTR.ConsultarLogoCTR();
            if(logo.next()){
                UtilVIEW.CarregaLabel(lblRelatorio, logo, "logotipo");
                txtNomeFantasia.setText(logo.getString("titulo"));
                txtTelefone1.setText(logo.getString("telefone1"));
                txtTelefone2.setText(logo.getString("telefone2"));
                
            }
        } catch (Exception e) {
            System.out.println(""+e.getMessage());
        }
    }
    private void SalvarConfiguracao(){
        try {
            if(objconfigurarCTR.CadastrarConfiguracaoCTR(txtNomeFantasia.getText().toUpperCase(), 
                    txtTelefone1.getText(), txtTelefone2.getText(), lblRelatorio.getText())){
                JOptionPane.showMessageDialog(null, "Salvo com sucesso!", "MENSAGEM", 
                        JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao salvar!", "MENSAGEM", 
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }
    private void AlterarImagemRelatorio(){
        try {
            objconfigurarCTR.AlterarImagemRelatorioCTR(lblRelatorio.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao Alterar Logotipo", "MENSAGEM", 
                    JOptionPane.WARNING_MESSAGE);
        }
    }
    private void AtualizarConfiguracao(){
        try {
            if(objconfigurarCTR.AlterarConfiguracaoCTR(txtNomeFantasia.getText().toUpperCase(), 
                    txtTelefone1.getText(), txtTelefone2.getText())){
                JOptionPane.showMessageDialog(null, "Atualizado com sucesso!", "MENSAGEM", 
                        JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao atualizar!", "MENSAGEM", 
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfiguracaoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfiguracaoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfiguracaoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfiguracaoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ConfiguracaoVIEW dialog = new ConfiguracaoVIEW(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblRelatorio;
    private javax.swing.JTextField txtNomeFantasia;
    private javax.swing.JTextField txtTelefone1;
    private javax.swing.JTextField txtTelefone2;
    // End of variables declaration//GEN-END:variables
}
