/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SolucaoSistemasVIEW;

import SolucaoSistemasCTR.ProdutoServicoCTR;
import SolucaoSistemasDAO.ProdutoServicoDAO;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;

/**
 *
 * @author Batman
 */
public class EtiquetaVIEW extends javax.swing.JDialog {

    Image carrega = null;
    ResultSet pegaLogo = null;
    DefaultListModel<String> dl = null;
    String valor = "";
    int indice = -1;
    ArrayList<ProdutoServicoDAO> nomes = new ArrayList<>();
    ArrayList<String> valores = new ArrayList<>();
    ArrayList<String> barraspegar = new ArrayList<>();
    ProdutoServicoDAO objProduto = new ProdutoServicoDAO();
    ResultSet consultaValor = null;

    /**
     * Creates new form EtiquetaVIEW
     */
    public EtiquetaVIEW(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        UtilVIEW.Icone(this);
        this.setTitle("ETIQUETAS");
        this.setLocationRelativeTo(null);
        this.setModal(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGerar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaProdutos = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaPreenche = new javax.swing.JList<>();
        btnAdicionaLista = new javax.swing.JButton();
        btnRemoveLista = new javax.swing.JButton();
        txtEtiquetas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/relatorio_32x32.png"))); // NOI18N
        btnGerar.setText("Visualizar");
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 4, 120, -1));

        listaProdutos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaProdutos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 230, 250));

        listaPreenche.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaPreenche);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 230, 250));

        btnAdicionaLista.setText(">");
        btnAdicionaLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionaListaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdicionaLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 60, 40));

        btnRemoveLista.setText("<");
        btnRemoveLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveListaActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemoveLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 60, 40));

        txtEtiquetas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEtiquetasKeyReleased(evt);
            }
        });
        getContentPane().add(txtEtiquetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 450, -1));

        setBounds(0, 0, 615, 347);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
        try {
            gerarEtiqueta();
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Valor nulo foi passado!");
        }

    }//GEN-LAST:event_btnGerarActionPerformed

    private void btnAdicionaListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionaListaActionPerformed
        try {
            dl = (DefaultListModel<String>) listaPreenche.getModel();
        } catch (Exception e) {
            dl = new DefaultListModel<>();

        }

        try {
            valor = listaProdutos.getSelectedValue();
            dl.addElement(valor);
            listaPreenche.setModel(dl);
            objProduto.setNome(String.valueOf(valor));
            objProduto.setReferencia("null");
            objProduto.setCodigobarras("null");
            objProduto.setCodigo("1");
            objProduto.setMargem("0");

            consultaValor = objProduto.ConsultarProdutoDAO();
            
            if (consultaValor.next()) {
                barraspegar.add(consultaValor.getString("nome"));
                valores.add(consultaValor.getString("codigobarras"));
            }
            valor = "";
            consultaValor = null;
            listaProdutos.clearSelection();
            txtEtiquetas.requestFocusInWindow();
        } catch (SQLException | ClassCastException e) {
            System.out.println("AQUI " + e.getMessage());
        }
    }//GEN-LAST:event_btnAdicionaListaActionPerformed
    private void btnRemoveListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveListaActionPerformed

        try {

            valor = listaPreenche.getSelectedValue();
            indice = listaPreenche.getSelectedIndex();
            dl = (DefaultListModel) listaPreenche.getModel();
            dl.removeElement(valor);
            barraspegar.remove(barraspegar.get(indice));
            valores.remove(valores.get(indice));
            listaPreenche.setModel(dl);
            txtEtiquetas.requestFocusInWindow();
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("" + e.getMessage());
        }


    }//GEN-LAST:event_btnRemoveListaActionPerformed

    private void txtEtiquetasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEtiquetasKeyReleased
        if (txtEtiquetas.getText().equals("")) {

        } else {
            ConsultarProdutos();
        }
    }//GEN-LAST:event_txtEtiquetasKeyReleased

    private void gerarEtiqueta() {
        try {
            URL arquivo = getClass().getResource("/Relatorios/etiquetas.jasper");
            Map parametros = new HashMap();
            
            for (int i = 0; i < barraspegar.size(); i++) {
                objProduto = new ProdutoServicoDAO();
                objProduto.setNome(String.valueOf(barraspegar.get(i)));
                objProduto.setCodigobarras(String.valueOf(valores.get(i)));
                nomes.add(objProduto);
            }
            JasperReport jr;
            jr = (JasperReport) JRLoader.loadObject(arquivo);
            JasperPrint print = null;
            print = JasperFillManager.fillReport(jr, parametros, new JRBeanCollectionDataSource(nomes));
            //JasperViewer view = new JasperViewer(print, false);
            JasperExportManager.exportReportToPdfFile(print, "/SolucaoSistemas/etiqueta.pdf");
            java.awt.Desktop.getDesktop().open(new File("/SolucaoSistemas/etiqueta.pdf"));
            //view.setVisible(true);
            nomes.clear();
        } catch (JRException | IOException ex) {
            System.out.println("" + ex.getMessage());
        }
    }

    private void ConsultarProdutos() {
        try {
            ProdutoServicoCTR objprodutoCTR = new ProdutoServicoCTR();
            ResultSet prod = null;
            dl = new DefaultListModel();
            dl.clear();
            prod = objprodutoCTR.GerarCodigoBarrasCTR(txtEtiquetas.getText().toUpperCase());
            prod.beforeFirst();
            while (prod.next()) {
                dl.addElement(prod.getString("nome"));
            }
            listaProdutos.setModel(dl);
           // dl.clear();
        } catch (SQLException e) {
            System.out.println("" + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EtiquetaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EtiquetaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EtiquetaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EtiquetaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                EtiquetaVIEW dialog = new EtiquetaVIEW(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionaLista;
    private javax.swing.JButton btnGerar;
    private javax.swing.JButton btnRemoveLista;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaPreenche;
    private javax.swing.JList<String> listaProdutos;
    private javax.swing.JTextField txtEtiquetas;
    // End of variables declaration//GEN-END:variables
}
