/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SolucaoSistemasVIEW;

import SolucaoSistemasCTR.AnimalCTR;
import SolucaoSistemasCTR.PessoaCTR;
import SolucaoSistemasCTR.ProdutoServicoCTR;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.ResultSet;
import javax.swing.ImageIcon;

/**
 *
 * @author Vinicius
 */
public class FotoVIEW extends javax.swing.JDialog {

    public static Image pegaImagem = null;
    ResultSet pegaIcone = null;
    String tipo;

    /**
     * Creates new form FotoVIEW
     *
     * @param parent
     * @param modal
     */
    public FotoVIEW(java.awt.Frame parent, boolean modal) {
//        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(400, 300);
        this.setTitle("FOTO");
        this.setModal(true);

        ConsultarImagemlVIEW("foto");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPesquisaFoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        lblPesquisaFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPesquisaFoto.setText("jLabel1");
        getContentPane().add(lblPesquisaFoto);
        lblPesquisaFoto.setBounds(0, 0, 400, 300);

        setBounds(0, 0, 416, 338);
    }// </editor-fold>//GEN-END:initComponents

    private void ConsultarImagemlVIEW(String col) {
        try {

            if (PesquisaAnimaisVIEW.telaAnimais == true) {
                col = "foto";
                AnimalCTR objanimalCTR = new AnimalCTR();
                pegaIcone = objanimalCTR.ConsultarAnimalCTR("null", "null", "2",
                        PesquisaAnimaisVIEW.codigoAnimal);
                PesquisaAnimaisVIEW.telaAnimais = false;
            } else if (PessoaVIEW.clicaFoto == true) {
                col = "foto";
                
                PessoaCTR objpessoaCTR = new PessoaCTR();
                if (PrincipalVIEW.cliente == true) {
                    tipo = "CLIENTE";
                } else if (PrincipalVIEW.funcionario == true) {
                    tipo = "FUNCIONARIO";
                } else if (PrincipalVIEW.fornecedor == true) {
                    tipo = "FORNECEDOR";
                } else if (PrincipalVIEW.empresa == true) {
                    tipo = "EMPRESA";
                } else if (PrincipalVIEW.veterinario == true) {
                    tipo = "VETERINARIO";
                }
               
               
                pegaIcone = objpessoaCTR.ConsultarPessoaCTR(
                        PessoaVIEW.txtCodigo.getText(), "null", tipo, "0");
            } else if (ProdutosServicosVIEW.fotoProduto == true
                    || PesquisaProdutosVIEW.telaProduto == true) {
                col = "imagem";
                ProdutoServicoCTR objprodutoCTR = new ProdutoServicoCTR();
                pegaIcone = objprodutoCTR.ConsultarProdutoCTR("null",
                        "null", "null", "1",
                        PesquisaProdutosVIEW.codigoProduto);

            }

            if (pegaIcone.next()) {

                pegaImagem
                        = Toolkit.getDefaultToolkit().createImage(pegaIcone.getBytes(col));
                lblPesquisaFoto.setIcon(
                        new ImageIcon(pegaImagem.getScaledInstance(
                                lblPesquisaFoto.getWidth(),
                                lblPesquisaFoto.getHeight(), Image.SCALE_DEFAULT)));

            }
        } catch (Exception e) {
            System.out.println("Fotos " + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FotoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FotoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FotoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FotoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FotoVIEW dialog = new FotoVIEW(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblPesquisaFoto;
    // End of variables declaration//GEN-END:variables
}
