/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SolucaoSistemasVIEW;

import SolucaoSistemasCTR.PermissaoCadastroCTR;
import SolucaoSistemasCTR.PermissaoFinanceiroCTR;
import SolucaoSistemasCTR.PermissaoRelatorioCTR;
import java.sql.Array;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author Batman
 */
public class PermissaoVIEW extends javax.swing.JDialog {

    PermissaoCadastroCTR objpermissaoCadastro = new PermissaoCadastroCTR();
    PermissaoFinanceiroCTR objpermissaoFinanceiro = new PermissaoFinanceiroCTR();
    PermissaoRelatorioCTR objpermissaoRelatorio = new PermissaoRelatorioCTR();

    /**
     * Creates new form PermissaoVIEW
     */
    public PermissaoVIEW(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("PERMISSÕES");
        UtilVIEW.Icone(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgOpcoes = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rbCaixa = new javax.swing.JRadioButton();
        rbContasReceber = new javax.swing.JRadioButton();
        rbContasPagar = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        rbEstoque = new javax.swing.JRadioButton();
        rbFinanceiro = new javax.swing.JRadioButton();
        rbPlanoContas = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        rbUsuario = new javax.swing.JRadioButton();
        rbCadPlanoContas = new javax.swing.JRadioButton();
        rbPermissoes = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtFuncionario = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        rbNovo = new javax.swing.JCheckBox();
        rbAtualizar = new javax.swing.JCheckBox();
        lblCodFuncionario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Financeiro"));
        jPanel1.setLayout(null);

        rbCaixa.setText("Caixa");
        jPanel1.add(rbCaixa);
        rbCaixa.setBounds(12, 16, 53, 23);

        rbContasReceber.setText("Contas a Receber");
        jPanel1.add(rbContasReceber);
        rbContasReceber.setBounds(12, 39, 111, 23);

        rbContasPagar.setText("Contas a Pagar");
        jPanel1.add(rbContasPagar);
        rbContasPagar.setBounds(12, 62, 99, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 130, 100);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Relatórios"));
        jPanel2.setLayout(null);

        rbEstoque.setText("Estoque");
        jPanel2.add(rbEstoque);
        rbEstoque.setBounds(12, 16, 65, 23);

        rbFinanceiro.setText("Financeiro");
        jPanel2.add(rbFinanceiro);
        rbFinanceiro.setBounds(12, 39, 75, 23);

        rbPlanoContas.setText("Plano de Contas");
        jPanel2.add(rbPlanoContas);
        rbPlanoContas.setBounds(12, 62, 120, 23);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(140, 10, 130, 100);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro"));
        jPanel3.setLayout(null);

        rbUsuario.setText("Usuário");
        jPanel3.add(rbUsuario);
        rbUsuario.setBounds(12, 16, 61, 23);

        rbCadPlanoContas.setText("Plano de Contas");
        jPanel3.add(rbCadPlanoContas);
        rbCadPlanoContas.setBounds(12, 39, 110, 23);

        rbPermissoes.setText("Permissões");
        jPanel3.add(rbPermissoes);
        rbPermissoes.setBounds(12, 62, 79, 23);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(280, 10, 130, 100);

        jLabel1.setText("Funcionário:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 120, 70, 14);

        txtFuncionario.setEditable(false);
        getContentPane().add(txtFuncionario);
        txtFuncionario.setBounds(10, 140, 270, 20);

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisar);
        btnPesquisar.setBounds(290, 140, 110, 23);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(290, 170, 110, 23);

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(290, 200, 110, 23);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Opções:"));
        jPanel4.setLayout(null);

        bgOpcoes.add(rbNovo);
        rbNovo.setText("Novo");
        jPanel4.add(rbNovo);
        rbNovo.setBounds(12, 16, 51, 23);

        bgOpcoes.add(rbAtualizar);
        rbAtualizar.setText("Atualizar");
        jPanel4.add(rbAtualizar);
        rbAtualizar.setBounds(12, 40, 67, 23);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(9, 170, 90, 70);

        lblCodFuncionario.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(lblCodFuncionario);
        lblCodFuncionario.setBounds(80, 116, 70, 20);

        setBounds(0, 0, 437, 288);
    }// </editor-fold>//GEN-END:initComponents
public static boolean permissaoFuncionario = false;
    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        permissaoFuncionario = true;
        new PesquisaDiversosVIEW(null, true).setVisible(true);
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed

        this.dispose();

    }//GEN-LAST:event_btnSairActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            if (rbNovo.isSelected() == false && rbAtualizar.isSelected() == false) {
                JOptionPane.showMessageDialog(null, "Escolher uma opção!", "MENSAGEM", 
                        JOptionPane.WARNING_MESSAGE);
            } else if (rbNovo.isSelected() == true) {
                CadastrarPermissaoCadastro(rbUsuario, rbCadPlanoContas, rbPermissoes);
                CadastrarPermissaoFinanceiro(rbCaixa, rbContasReceber, rbContasPagar);
                CadastrarPermissaoRelatorio(rbEstoque, rbFinanceiro, rbPlanoContas);
                JOptionPane.showMessageDialog(null, "Salvo com sucesso!", "MENSAGEM", 
                        JOptionPane.INFORMATION_MESSAGE);

            } else if (rbAtualizar.isSelected() == true) {
                AtualizarPermissaoCadastro(rbUsuario, rbCadPlanoContas, rbPermissoes);
                AtualizarPermissaoFinanceiro(rbCaixa, rbContasReceber, rbContasPagar);
                AtualizarPermissaoRelatorio(rbEstoque, rbFinanceiro, rbPlanoContas);
                JOptionPane.showMessageDialog(null, "Atualizado com sucesso!", "MENSAGEM", 
                        JOptionPane.INFORMATION_MESSAGE);

            }

            lblCodFuncionario.setText("");
            txtFuncionario.setText("");
            UtilVIEW.LimparSelecao(jPanel1);
            UtilVIEW.LimparSelecao(jPanel2);
            UtilVIEW.LimparSelecao(jPanel3);
            UtilVIEW.LimparSelecao(jPanel4);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro no botão Salvar", "MENSAGEM", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed
    ArrayList<String> lista = new ArrayList<>();

    private void CadastrarPermissaoCadastro(JRadioButton... radios) {
        try {
            for (int i = 0; i < radios.length; i++) {
                if (radios[i].isSelected() == false) {
                    lista.add("NAO");
                } else if (radios[i].isSelected() == true) {
                    lista.add("SIM");
                }
            }

            objpermissaoCadastro.CadastrarPermissaoCadastroCTR(lista.get(0), lista.get(1), lista.get(2),
                    lblCodFuncionario.getText());
            lista.clear();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao CadastrarPermissaoCadastro",
                    "MENSAGEM", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void AtualizarPermissaoCadastro(JRadioButton... radios) {
        try {
            for (int i = 0; i < radios.length; i++) {
                if (radios[i].isSelected() == false) {
                    lista.add("NAO");
                } else if (radios[i].isSelected() == true) {
                    lista.add("SIM");
                }
            }

            objpermissaoCadastro.AlterarPermissaoCadastroCTR(lista.get(0), lista.get(1),
                    lista.get(2), lblCodFuncionario.getText());
            lista.clear();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao AtualizarPermissaoCadastro",
                    "MENSAGEM", JOptionPane.WARNING_MESSAGE);
            System.out.println("" + e.getMessage());
        }
    }

    private void CadastrarPermissaoFinanceiro(JRadioButton... radios) {
        try {
            for (int i = 0; i < radios.length; i++) {
                if (radios[i].isSelected() == false) {
                    lista.add("NAO");
                } else if (radios[i].isSelected() == true) {
                    lista.add("SIM");
                }
            }

            objpermissaoFinanceiro.CadastrarPermissaoFinanceiroCTR(lista.get(0), lista.get(1), lista.get(2),
                    lblCodFuncionario.getText());
            lista.clear();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao CadastrarPermissaoFinanceiro",
                    "MENSAGEM", JOptionPane.WARNING_MESSAGE);
            System.out.println("" + e.getMessage());
        }
    }

    private void AtualizarPermissaoFinanceiro(JRadioButton... radios) {
        try {
            for (int i = 0; i < radios.length; i++) {
                if (radios[i].isSelected() == false) {
                    lista.add("NAO");
                } else if (radios[i].isSelected() == true) {
                    lista.add("SIM");
                }
            }

            objpermissaoFinanceiro.AlterarPermissaoFinanceiroCTR(lista.get(0), lista.get(1), lista.get(2),
                    lblCodFuncionario.getText());
            lista.clear();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao AtualizarPermissaoFinanceiro",
                    "MENSAGEM", JOptionPane.WARNING_MESSAGE);
            System.out.println("" + e.getMessage());
        }
    }

    private void CadastrarPermissaoRelatorio(JRadioButton... radios) {
        try {
            for (int i = 0; i < radios.length; i++) {
                if (radios[i].isSelected() == false) {
                    lista.add("NAO");
                } else if (radios[i].isSelected() == true) {
                    lista.add("SIM");
                }
            }

            objpermissaoRelatorio.CadastrarPermissaoRelatorioCTR(lista.get(0), lista.get(1), lista.get(2),
                    "NAO", lblCodFuncionario.getText());
            lista.clear();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao CadastrarPermissaoRelatorio",
                    "MENSAGEM", JOptionPane.WARNING_MESSAGE);
            System.out.println("" + e.getMessage());
        }
    }

    private void AtualizarPermissaoRelatorio(JRadioButton... radios) {
        try {
            for (int i = 0; i < radios.length; i++) {
                if (radios[i].isSelected() == false) {
                    lista.add("NAO");
                } else if (radios[i].isSelected() == true) {
                    lista.add("SIM");
                }
            }

            objpermissaoRelatorio.AlterarPermissaoRelatorioCTR(lista.get(0), lista.get(1), lista.get(2),
                    "NAO", lblCodFuncionario.getText());
            lista.clear();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao AtualizarPermissaoRelatorio",
                    "MENSAGEM", JOptionPane.WARNING_MESSAGE);
            System.out.println("" + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PermissaoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PermissaoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PermissaoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PermissaoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                PermissaoVIEW dialog = new PermissaoVIEW(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgOpcoes;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JLabel lblCodFuncionario;
    private javax.swing.JCheckBox rbAtualizar;
    private javax.swing.JRadioButton rbCadPlanoContas;
    private javax.swing.JRadioButton rbCaixa;
    private javax.swing.JRadioButton rbContasPagar;
    private javax.swing.JRadioButton rbContasReceber;
    private javax.swing.JRadioButton rbEstoque;
    private javax.swing.JRadioButton rbFinanceiro;
    private javax.swing.JCheckBox rbNovo;
    private javax.swing.JRadioButton rbPermissoes;
    private javax.swing.JRadioButton rbPlanoContas;
    private javax.swing.JRadioButton rbUsuario;
    public static javax.swing.JTextField txtFuncionario;
    // End of variables declaration//GEN-END:variables
}
