/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SolucaoSistemasVIEW;

import SolucaoSistemasCTR.AnimalCTR;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vinicius
 */
public class PesquisaAnimaisVIEW extends javax.swing.JDialog {

    String ordene = "";
    AnimalCTR objanimalCTR = new AnimalCTR();
    UtilVIEW objutil = new UtilVIEW();
    public static String codigoAnimal = "";

    /**
     * Creates new form PesquisaAnimaisVIEW
     *
     * @param parent
     * @param modal
     */
    public PesquisaAnimaisVIEW(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tblPesquisaAnimal.setDefaultRenderer(Object.class, new ColorRenderer());
        this.setLocationRelativeTo(null);
        this.setTitle("PESQUISA DE ANIMAIS");
        tblPesquisaAnimal.getColumnModel().getColumn(1).setMinWidth(200);
        tblPesquisaAnimal.getColumnModel().getColumn(2).setMinWidth(100);
        tblPesquisaAnimal.getColumnModel().getColumn(3).setMinWidth(100);
        tblPesquisaAnimal.getColumnModel().getColumn(4).setMinWidth(100);
        tblPesquisaAnimal.getColumnModel().getColumn(5).setMinWidth(200);
        tblPesquisaAnimal.getColumnModel().getColumn(6).setMinWidth(200);
        tblPesquisaAnimal.getColumnModel().getColumn(7).setMinWidth(100);
        tblPesquisaAnimal.getColumnModel().getColumn(8).setMinWidth(200);
        tblPesquisaAnimal.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        txtPesquisaAnimal.requestFocusInWindow();
        UtilVIEW.Icone(this);
        ConsultarAnimalVIEW("", "null", "2", "null");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbxOrdemAnimal = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtPesquisaAnimal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPesquisaDono = new javax.swing.JTextField();
        lblIncluir = new javax.swing.JLabel();
        lblAlterar = new javax.swing.JLabel();
        lblImprimir = new javax.swing.JLabel();
        lblImagem = new javax.swing.JLabel();
        lblCalendario = new javax.swing.JLabel();
        lblSair = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPesquisaAnimal = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Ordem da Pesquisa");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 110, 14);

        cbxOrdemAnimal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Por Codigo", "Por Nome", "Por Raça", "Por Especie" }));
        cbxOrdemAnimal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxOrdemAnimalItemStateChanged(evt);
            }
        });
        getContentPane().add(cbxOrdemAnimal);
        cbxOrdemAnimal.setBounds(10, 30, 120, 20);

        jLabel2.setText("Pesquisa pelo nome do Animal");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 10, 190, 14);

        txtPesquisaAnimal.setBackground(new java.awt.Color(255, 255, 204));
        txtPesquisaAnimal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisaAnimalKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaAnimalKeyReleased(evt);
            }
        });
        getContentPane().add(txtPesquisaAnimal);
        txtPesquisaAnimal.setBounds(150, 30, 190, 20);

        jLabel3.setText("Pesquisa pelo nome do Dono");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(350, 10, 180, 14);

        txtPesquisaDono.setBackground(new java.awt.Color(255, 255, 204));
        txtPesquisaDono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaDonoKeyReleased(evt);
            }
        });
        getContentPane().add(txtPesquisaDono);
        txtPesquisaDono.setBounds(350, 30, 190, 20);

        lblIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/8390_32x32.png"))); // NOI18N
        lblIncluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIncluirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIncluirMouseEntered(evt);
            }
        });
        getContentPane().add(lblIncluir);
        lblIncluir.setBounds(550, 10, 30, 40);

        lblAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/8416_32x32.png"))); // NOI18N
        lblAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAlterarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAlterarMouseEntered(evt);
            }
        });
        getContentPane().add(lblAlterar);
        lblAlterar.setBounds(590, 10, 30, 40);

        lblImprimir.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Imprimir_32x32.png"))); // NOI18N
        lblImprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImprimirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblImprimirMouseEntered(evt);
            }
        });
        getContentPane().add(lblImprimir);
        lblImprimir.setBounds(620, 10, 40, 40);

        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/foto_32x32.png"))); // NOI18N
        lblImagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblImagemMouseEntered(evt);
            }
        });
        getContentPane().add(lblImagem);
        lblImagem.setBounds(667, 10, 30, 40);

        lblCalendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/calendario_32x32.png"))); // NOI18N
        lblCalendario.setText("jLabel8");
        lblCalendario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCalendarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCalendarioMouseEntered(evt);
            }
        });
        getContentPane().add(lblCalendario);
        lblCalendario.setBounds(710, 10, 30, 40);

        lblSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/casa_32x32.png"))); // NOI18N
        lblSair.setText("jLabel9");
        lblSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSairMouseEntered(evt);
            }
        });
        getContentPane().add(lblSair);
        lblSair.setBounds(750, 10, 30, 40);

        tblPesquisaAnimal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome do Animal", "Sexo", "Especie", "Raça", "Cor e Informações Complementares", "Nome do Dono", "Peso Atual", "Foto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPesquisaAnimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPesquisaAnimalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPesquisaAnimal);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 770, 300);

        setBounds(0, 0, 807, 411);
    }// </editor-fold>//GEN-END:initComponents

    private void lblIncluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIncluirMouseClicked
        new AnimaisVIEW(null, true).setVisible(true);
        ConsultarAnimalVIEW("", "null", "2", "null");
    }//GEN-LAST:event_lblIncluirMouseClicked

    private void lblIncluirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIncluirMouseEntered
        lblIncluir.setToolTipText("Incluir");
    }//GEN-LAST:event_lblIncluirMouseEntered

    private void lblAlterarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAlterarMouseEntered

        lblAlterar.setToolTipText("Alterar");
    }//GEN-LAST:event_lblAlterarMouseEntered

    private void lblImprimirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImprimirMouseEntered
        lblImprimir.setToolTipText("Imprimir");
    }//GEN-LAST:event_lblImprimirMouseEntered

    private void lblImagemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagemMouseEntered
        lblImagem.setToolTipText("Imagem");
    }//GEN-LAST:event_lblImagemMouseEntered

    private void lblCalendarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCalendarioMouseEntered
        lblCalendario.setToolTipText("Aniverário");
    }//GEN-LAST:event_lblCalendarioMouseEntered

    private void lblSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseEntered
        lblSair.setToolTipText("Sair");
    }//GEN-LAST:event_lblSairMouseEntered

    private void txtPesquisaAnimalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaAnimalKeyPressed
        try {
            if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
                txtPesquisaDono.requestFocusInWindow();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtPesquisaAnimalKeyPressed

    private void cbxOrdemAnimalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxOrdemAnimalItemStateChanged
        try {
            switch (cbxOrdemAnimal.getSelectedIndex()) {
                case 0:
                    ordene = "2";
                    ConsultarAnimalVIEW("", "null", ordene, "0");
                    ordene = "";
                    break;
                case 1:
                    ordene = "1";
                    ConsultarAnimalVIEW("", "null", ordene, "0");
                    ordene = "";
                    break;
                case 2:
                    ordene = "2";
                    ConsultarAnimalVIEW("", "null", ordene, "0");
                    ordene = "";
                    break;
                case 3:
                    ordene = "7";
                    ConsultarAnimalVIEW("", "null", ordene, "0");
                    ordene = "";
                    break;
                case 4:
                    ordene = "6";
                    ConsultarAnimalVIEW("", "null", ordene, "0");
                    ordene = "";
                    break;
                default:
                    ordene = "2";
                    ConsultarAnimalVIEW("", "null", ordene, "0");
                    ordene = "";
                    break;

            }
        } catch (Exception e) {
            System.out.println("" + e.getMessage());
        }


    }//GEN-LAST:event_cbxOrdemAnimalItemStateChanged

    private void txtPesquisaAnimalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaAnimalKeyReleased

        ConsultarAnimalVIEW(txtPesquisaAnimal.getText().toUpperCase(), "null", "2", "0");
    }//GEN-LAST:event_txtPesquisaAnimalKeyReleased

    private void txtPesquisaDonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaDonoKeyReleased

        ConsultarAnimalVIEW("null", txtPesquisaDono.getText().toUpperCase(), "2", "0");
    }//GEN-LAST:event_txtPesquisaDonoKeyReleased
    public static boolean telaAnimais = false;
    private void lblImagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagemMouseClicked

        telaAnimais = true;
        codigoAnimal = tblPesquisaAnimal.getValueAt(
                tblPesquisaAnimal.getSelectedRow(), 0).toString();
        new FotoVIEW(null, true).setVisible(true);

    }//GEN-LAST:event_lblImagemMouseClicked

    private void lblAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAlterarMouseClicked
        try {
            this.dispose();
            codigoAnimal = String.valueOf(tblPesquisaAnimal.getValueAt(
                    tblPesquisaAnimal.getSelectedRow(), 0));
            new AnimaisVIEW(null, true).setVisible(true);
            ConsultarAnimalVIEW("", "null", "2", "null");
        } catch (ArrayIndexOutOfBoundsException | NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Selecionar o animal!",
                    "MENSAGEM", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_lblAlterarMouseClicked

    private void lblSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseClicked
        int sair = -1;
        sair = JOptionPane.showConfirmDialog(null, "Deseja sair?", "MENSAGEM",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (sair == 0) {
            this.dispose();
        } else if (sair == 1) {

        }
    }//GEN-LAST:event_lblSairMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        txtPesquisaAnimal.requestFocusInWindow();
    }//GEN-LAST:event_formWindowOpened

    private void lblCalendarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCalendarioMouseClicked
        this.dispose();
        objutil.ImprimirAniversarioAnimal();
    }//GEN-LAST:event_lblCalendarioMouseClicked

    private void lblImprimirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImprimirMouseClicked
        this.dispose();
        objutil.ImprimirAnimais();

    }//GEN-LAST:event_lblImprimirMouseClicked

    private void tblPesquisaAnimalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPesquisaAnimalMouseClicked
        try {

            if (evt.getClickCount() == 2) {
                if (AgendamentoVIEW.agendarAnimal == true) {
                    AgendamentoVIEW.codigoAnimal = String.valueOf(
                            tblPesquisaAnimal.getValueAt(tblPesquisaAnimal.getSelectedRow(), 0));
                    AgendamentoVIEW.txtNomeAnimal.setText(String.valueOf(
                            tblPesquisaAnimal.getValueAt(tblPesquisaAnimal.getSelectedRow(), 1)));
                    AgendamentoVIEW.txtCliente.setText(String.valueOf(
                            tblPesquisaAnimal.getValueAt(tblPesquisaAnimal.getSelectedRow(), 6)));
                    AgendamentoVIEW.cbxAtendente.requestFocusInWindow();
                    AgendamentoVIEW.agendarAnimal = false;
                } else if (AtendimentoVIEW.animalAtendimento == true) {
                    AtendimentoVIEW.atendimentoAnimal = String.valueOf(
                            tblPesquisaAnimal.getValueAt(tblPesquisaAnimal.getSelectedRow(), 0));
                    AtendimentoVIEW.txtNomeAnimal.setText(String.valueOf(
                            tblPesquisaAnimal.getValueAt(tblPesquisaAnimal.getSelectedRow(), 1)));
                    if (String.valueOf(
                            tblPesquisaAnimal.getValueAt(tblPesquisaAnimal.getSelectedRow(), 2)).equals("MACHO")) {
                        AtendimentoVIEW.rbMacho.setSelected(true);
                        AtendimentoVIEW.rbFemea.setSelected(false);
                    } else if (String.valueOf(
                            tblPesquisaAnimal.getValueAt(tblPesquisaAnimal.getSelectedRow(), 2)).equals("FEMEA")) {
                        AtendimentoVIEW.rbMacho.setSelected(false);
                        AtendimentoVIEW.rbFemea.setSelected(true);
                    }
                    AtendimentoVIEW.txtPesoAtual.setText(String.valueOf(
                            tblPesquisaAnimal.getValueAt(tblPesquisaAnimal.getSelectedRow(), 7)));
                    AtendimentoVIEW.txtEspecie.setText(String.valueOf(
                            tblPesquisaAnimal.getValueAt(tblPesquisaAnimal.getSelectedRow(), 3)));
                    AtendimentoVIEW.txtRaca.setText(String.valueOf(
                            tblPesquisaAnimal.getValueAt(tblPesquisaAnimal.getSelectedRow(), 4)));
                    AtendimentoVIEW.txtCor.setText(String.valueOf(
                            tblPesquisaAnimal.getValueAt(tblPesquisaAnimal.getSelectedRow(), 5)));
                    AtendimentoVIEW.txtAcessorios.requestFocusInWindow();

                }

                this.dispose();
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_tblPesquisaAnimalMouseClicked

    private void ConsultarAnimalVIEW(String nome, String dono, String ordem, String identificacao) {
        try {
            ResultSet consultaAnimal = null;
            consultaAnimal = objanimalCTR.ConsultarAnimalCTR(nome, dono, ordem, identificacao);
            RestaurarAnimalVIEW(consultaAnimal);
        } catch (Exception e) {
            System.out.println("" + e.getMessage());
        }
    }

    private void RestaurarAnimalVIEW(ResultSet rs) {
        try {
            DefaultTableModel dtm = (DefaultTableModel) tblPesquisaAnimal.getModel();
            dtm.setRowCount(0);
            while (rs.next()) {
                dtm.addRow(new Object[]{rs.getString("codigo"), rs.getString("nomeanimal"),
                    rs.getString("sexo"), rs.getString("especie"), rs.getString("raca"),
                    rs.getString("identificacao"), rs.getString("nome"), String.format("%.3f", rs.getDouble("peso")),
                    rs.getString("foto")});
            }
        } catch (Exception e) {
            System.out.println("" + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisaAnimaisVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisaAnimaisVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisaAnimaisVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisaAnimaisVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                PesquisaAnimaisVIEW dialog = new PesquisaAnimaisVIEW(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbxOrdemAnimal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAlterar;
    private javax.swing.JLabel lblCalendario;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblImprimir;
    private javax.swing.JLabel lblIncluir;
    private javax.swing.JLabel lblSair;
    public static javax.swing.JTable tblPesquisaAnimal;
    private javax.swing.JTextField txtPesquisaAnimal;
    private javax.swing.JTextField txtPesquisaDono;
    // End of variables declaration//GEN-END:variables
}
