/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SolucaoSistemasVIEW;

import SolucaoSistemasCTR.PessoaCTR;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vinicius
 */
public class PessoaVIEW extends javax.swing.JDialog {

    PessoaCTR objpessoaCTR = new PessoaCTR();
    String tipo = "", liberado = "", bloqueado = "";
    ResultSet pessoa = null;

    /**
     * Creates new form PessoaVIEW
     *
     * @param parent
     * @param modal
     */
    public PessoaVIEW(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
      
        UtilVIEW.ImagemLabel("\\SolucaoSistemas\\src\\Imagem\\semFoto.jpg", lblFoto);

        rbLiberado.setSelected(true);
        rbNovo.setSelected(true);
        UtilVIEW.mascaraCnpj(txtCnpj);
        UtilVIEW.mascaraCpf(txtCpf);
        UtilVIEW.mascaraData(txtNascimento);
        UtilVIEW.Icone(this);
        txtSigla.setDocument(new FixedLenghtDocument(2));
        if (PrincipalVIEW.cliente == true) {
            tipo = "CLIENTE";
        } else if (PrincipalVIEW.funcionario == true) {
            tipo = "FUNCIONARIO";
        } else if (PrincipalVIEW.fornecedor == true) {
            tipo = "FORNECEDOR";
        } else if (PrincipalVIEW.empresa == true) {
            tipo = "EMPRESA";
        } else if (PrincipalVIEW.veterinario == true) {
            tipo = "VETERINARIO";
        }
        tblPessoa.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblPessoa.getColumnModel().getColumn(1).setMinWidth(200);
        tblPessoa.getColumnModel().getColumn(2).setMinWidth(200);
        tblPessoa.getColumnModel().getColumn(3).setMinWidth(100);
        tblPessoa.getColumnModel().getColumn(4).setMinWidth(100);
        tblPessoa.getColumnModel().getColumn(5).setMinWidth(100);
        tblPessoa.getColumnModel().getColumn(6).setMinWidth(100);
        tblPessoa.getColumnModel().getColumn(7).setMinWidth(100);
        tblPessoa.getColumnModel().getColumn(8).setMinWidth(200);
        tblPessoa.getColumnModel().getColumn(9).setMinWidth(200);
        tblPessoa.getColumnModel().getColumn(10).setMinWidth(200);
        tblPessoa.getColumnModel().getColumn(12).setMinWidth(200);
        tblPessoa.getColumnModel().getColumn(13).setMinWidth(200);
        tblPessoa.getColumnModel().getColumn(14).setMinWidth(100);
        tblPessoa.getColumnModel().getColumn(15).setMinWidth(100);
        tblPessoa.getColumnModel().getColumn(16).setMinWidth(200);
        tblPessoa.getColumnModel().getColumn(17).setMinWidth(100);

        tblPessoa.setDefaultRenderer(Object.class, new ColorRenderer());
        this.setTitle("CADASTRO DE " + tipo);
        ConsultarPessoaVIEW("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoOpcoes = new javax.swing.ButtonGroup();
        grupoBloquear = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApelido = new javax.swing.JTextField();
        pnlOpcoes = new javax.swing.JPanel();
        rbNovo = new javax.swing.JRadioButton();
        rbAlterar = new javax.swing.JRadioButton();
        pnlOperacao = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        txtRG = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTelefone1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTelefone2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNascimento = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        txtFacebook = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtInstagram = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtObservacao = new javax.swing.JTextField();
        txtCnpj = new javax.swing.JFormattedTextField();
        rbBloqueado = new javax.swing.JRadioButton();
        rbLiberado = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPessoa = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtSigla = new javax.swing.JTextField();
        btnFoto = new javax.swing.JButton();
        lblFoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setText("Código:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 50, 14);

        txtCodigo.setEditable(false);
        jPanel1.add(txtCodigo);
        txtCodigo.setBounds(10, 30, 60, 20);

        jLabel2.setText("Nome / Razão Social: ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 10, 110, 14);

        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeFocusLost(evt);
            }
        });
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeKeyReleased(evt);
            }
        });
        jPanel1.add(txtNome);
        txtNome.setBounds(80, 30, 320, 20);

        jLabel3.setText("Apelido / Nome Fantasia:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(410, 10, 280, 14);

        txtApelido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtApelidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApelidoFocusLost(evt);
            }
        });
        txtApelido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtApelidoKeyPressed(evt);
            }
        });
        jPanel1.add(txtApelido);
        txtApelido.setBounds(410, 30, 320, 20);

        pnlOpcoes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opções:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 10))); // NOI18N
        pnlOpcoes.setLayout(null);

        grupoOpcoes.add(rbNovo);
        rbNovo.setText("Novo");
        rbNovo.setOpaque(false);
        rbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNovoActionPerformed(evt);
            }
        });
        pnlOpcoes.add(rbNovo);
        rbNovo.setBounds(10, 18, 70, 23);

        grupoOpcoes.add(rbAlterar);
        rbAlterar.setText("Atualizar");
        rbAlterar.setOpaque(false);
        pnlOpcoes.add(rbAlterar);
        rbAlterar.setBounds(10, 38, 70, 23);

        jPanel1.add(pnlOpcoes);
        pnlOpcoes.setBounds(740, 10, 100, 70);

        pnlOperacao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operação:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 10))); // NOI18N
        pnlOperacao.setLayout(null);

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/disquete_16x16.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        pnlOperacao.add(btnSalvar);
        btnSalvar.setBounds(10, 20, 90, 25);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Fechar_16x16.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        pnlOperacao.add(btnSair);
        btnSair.setBounds(10, 50, 90, 25);

        jPanel1.add(pnlOperacao);
        pnlOperacao.setBounds(740, 89, 110, 90);

        jLabel4.setText("Cpf:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 60, 70, 14);

        txtCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCpfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCpfFocusLost(evt);
            }
        });
        txtCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCpfKeyPressed(evt);
            }
        });
        jPanel1.add(txtCpf);
        txtCpf.setBounds(10, 80, 110, 20);

        jLabel5.setText("Rg/CRMV:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(130, 60, 50, 14);

        txtRG.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRGFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRGFocusLost(evt);
            }
        });
        txtRG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRGKeyPressed(evt);
            }
        });
        jPanel1.add(txtRG);
        txtRG.setBounds(130, 80, 110, 20);

        jLabel6.setText("Data de Nascimento:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(250, 60, 130, 14);

        jLabel7.setText("Telefone 1:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(370, 60, 80, 14);

        txtTelefone1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelefone1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelefone1FocusLost(evt);
            }
        });
        txtTelefone1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelefone1KeyPressed(evt);
            }
        });
        jPanel1.add(txtTelefone1);
        txtTelefone1.setBounds(370, 80, 110, 20);

        jLabel8.setText("Telefone 2:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(490, 60, 70, 14);

        txtTelefone2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelefone2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelefone2FocusLost(evt);
            }
        });
        txtTelefone2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelefone2KeyPressed(evt);
            }
        });
        jPanel1.add(txtTelefone2);
        txtTelefone2.setBounds(490, 80, 110, 20);

        jLabel9.setText("Cnpj:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(610, 60, 50, 14);

        txtNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNascimentoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNascimentoFocusLost(evt);
            }
        });
        txtNascimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNascimentoKeyPressed(evt);
            }
        });
        jPanel1.add(txtNascimento);
        txtNascimento.setBounds(250, 80, 110, 20);

        jLabel10.setText("Facebook:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 110, 70, 14);

        txtFacebook.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFacebookFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFacebookFocusLost(evt);
            }
        });
        txtFacebook.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFacebookKeyPressed(evt);
            }
        });
        jPanel1.add(txtFacebook);
        txtFacebook.setBounds(10, 130, 200, 20);

        jLabel11.setText("Instagram:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(220, 110, 80, 14);

        txtInstagram.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtInstagramFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtInstagramFocusLost(evt);
            }
        });
        txtInstagram.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInstagramKeyPressed(evt);
            }
        });
        jPanel1.add(txtInstagram);
        txtInstagram.setBounds(220, 130, 200, 20);

        jLabel12.setText("Email:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(430, 110, 100, 14);

        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
        });
        jPanel1.add(txtEmail);
        txtEmail.setBounds(430, 130, 200, 20);

        jLabel13.setText("Observações/Restrições:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 250, 190, 14);

        txtObservacao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtObservacaoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtObservacaoFocusLost(evt);
            }
        });
        jPanel1.add(txtObservacao);
        txtObservacao.setBounds(10, 270, 830, 20);

        txtCnpj.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCnpjFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCnpjFocusLost(evt);
            }
        });
        txtCnpj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCnpjKeyPressed(evt);
            }
        });
        jPanel1.add(txtCnpj);
        txtCnpj.setBounds(610, 80, 120, 20);

        grupoBloquear.add(rbBloqueado);
        rbBloqueado.setText("Bloqueado");
        jPanel1.add(rbBloqueado);
        rbBloqueado.setBounds(640, 110, 93, 23);

        grupoBloquear.add(rbLiberado);
        rbLiberado.setText("Liberado");
        jPanel1.add(rbLiberado);
        rbLiberado.setBounds(640, 130, 90, 23);

        tblPessoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código:", "Nome / Razão Social:", "Apelido/Nome Fantasia:", "Telefone1:", "Telefone2:", "Cpf:", "Cnpj:", "Rg:", "Endereço:", "Bairro:", "Cidade:", "Sigla:", "Email", "Facebook:", "Instagram", "Nascimento:", "Observações/Restrições:", "Foto:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPessoa.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblPessoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPessoaMouseClicked(evt);
            }
        });
        tblPessoa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblPessoaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblPessoa);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 300, 830, 170);

        jLabel14.setText("Endereço:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(10, 160, 90, 14);

        txtEndereco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEnderecoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEnderecoFocusLost(evt);
            }
        });
        txtEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEnderecoKeyPressed(evt);
            }
        });
        jPanel1.add(txtEndereco);
        txtEndereco.setBounds(10, 180, 410, 20);

        jLabel15.setText("Bairro:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(430, 160, 100, 14);

        txtBairro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBairroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBairroFocusLost(evt);
            }
        });
        txtBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBairroKeyPressed(evt);
            }
        });
        jPanel1.add(txtBairro);
        txtBairro.setBounds(430, 180, 410, 20);

        jLabel16.setText("Cidade:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(10, 206, 110, 14);

        txtCidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCidadeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCidadeFocusLost(evt);
            }
        });
        txtCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCidadeKeyPressed(evt);
            }
        });
        jPanel1.add(txtCidade);
        txtCidade.setBounds(10, 224, 410, 20);

        jLabel17.setText("Estado/Sigla:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(430, 206, 70, 14);

        txtSigla.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSiglaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSiglaFocusLost(evt);
            }
        });
        txtSigla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSiglaKeyPressed(evt);
            }
        });
        jPanel1.add(txtSigla);
        txtSigla.setBounds(430, 224, 60, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(130, 0, 860, 480);

        btnFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/lupa_16x16.png"))); // NOI18N
        btnFoto.setText("Procurar");
        btnFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFotoActionPerformed(evt);
            }
        });
        getContentPane().add(btnFoto);
        btnFoto.setBounds(0, 134, 130, 25);

        lblFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFotoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblFotoMouseEntered(evt);
            }
        });
        getContentPane().add(lblFoto);
        lblFoto.setBounds(2, 2, 130, 130);

        setBounds(0, 0, 996, 515);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyPressed
        try {
            if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
                txtApelido.requestFocusInWindow();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtNomeKeyPressed

    private void txtApelidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApelidoKeyPressed
        try {
            if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
                txtCpf.requestFocusInWindow();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtApelidoKeyPressed

    private void txtCpfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpfKeyPressed
        try {
            if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
                txtRG.requestFocusInWindow();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtCpfKeyPressed

    private void txtRGKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRGKeyPressed
        try {
            if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
                txtNascimento.requestFocusInWindow();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtRGKeyPressed

    private void txtNascimentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNascimentoKeyPressed
        try {
            if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
                txtTelefone1.requestFocusInWindow();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtNascimentoKeyPressed

    private void txtTelefone1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefone1KeyPressed
        try {
            if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
                txtTelefone2.requestFocusInWindow();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtTelefone1KeyPressed

    private void txtTelefone2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefone2KeyPressed
        try {
            if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
                txtCnpj.requestFocusInWindow();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtTelefone2KeyPressed

    private void txtCnpjKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCnpjKeyPressed
        try {
            if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
                txtFacebook.requestFocusInWindow();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtCnpjKeyPressed

    private void txtFacebookKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFacebookKeyPressed
        try {
            if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
                txtInstagram.requestFocusInWindow();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtFacebookKeyPressed

    private void txtInstagramKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInstagramKeyPressed
        try {
            if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
                txtEmail.requestFocusInWindow();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtInstagramKeyPressed

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        try {
            if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
                txtEndereco.requestFocusInWindow();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtEmailKeyPressed

    private void txtNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusGained
        try {
            txtNome.setBackground(new Color(255, 255, 204));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtNomeFocusGained

    private void txtApelidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApelidoFocusGained
        try {
            txtApelido.setBackground(new Color(255, 255, 204));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtApelidoFocusGained

    private void txtCpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCpfFocusGained
        try {
            txtCpf.setBackground(new Color(255, 255, 204));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtCpfFocusGained

    private void txtRGFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRGFocusGained
        try {
            txtRG.setBackground(new Color(255, 255, 204));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtRGFocusGained

    private void txtNascimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNascimentoFocusGained
        try {
            txtNascimento.setBackground(new Color(255, 255, 204));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtNascimentoFocusGained

    private void txtTelefone1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefone1FocusGained
        try {
            txtTelefone1.setBackground(new Color(255, 255, 204));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtTelefone1FocusGained

    private void txtTelefone2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefone2FocusGained
        try {
            txtTelefone2.setBackground(new Color(255, 255, 204));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtTelefone2FocusGained

    private void txtCnpjFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCnpjFocusGained
        try {
            txtCnpj.setBackground(new Color(255, 255, 204));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtCnpjFocusGained

    private void txtFacebookFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFacebookFocusGained
        try {
            txtFacebook.setBackground(new Color(255, 255, 204));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtFacebookFocusGained

    private void txtInstagramFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInstagramFocusGained
        try {
            txtInstagram.setBackground(new Color(255, 255, 204));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtInstagramFocusGained

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        try {
            txtEmail.setBackground(new Color(255, 255, 204));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtObservacaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtObservacaoFocusGained
        try {
            txtObservacao.setBackground(new Color(255, 255, 204));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtObservacaoFocusGained

    private void txtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusLost
        try {
            txtNome.setBackground(Color.white);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtNomeFocusLost

    private void txtApelidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApelidoFocusLost
        try {
            txtApelido.setBackground(Color.white);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtApelidoFocusLost

    private void txtCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCpfFocusLost
        try {
            txtCpf.setBackground(Color.white);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtCpfFocusLost

    private void txtRGFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRGFocusLost
        try {
            txtRG.setBackground(Color.white);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtRGFocusLost

    private void txtNascimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNascimentoFocusLost
        try {
            txtNascimento.setBackground(Color.white);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtNascimentoFocusLost

    private void txtTelefone1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefone1FocusLost
        try {
            txtTelefone1.setBackground(Color.white);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtTelefone1FocusLost

    private void txtTelefone2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefone2FocusLost
        try {
            txtTelefone2.setBackground(Color.white);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtTelefone2FocusLost

    private void txtCnpjFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCnpjFocusLost
        try {
            txtCnpj.setBackground(Color.white);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtCnpjFocusLost

    private void txtFacebookFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFacebookFocusLost
        try {
            txtFacebook.setBackground(Color.white);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtFacebookFocusLost

    private void txtInstagramFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInstagramFocusLost
        try {
            txtInstagram.setBackground(Color.white);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtInstagramFocusLost

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        try {
            txtEmail.setBackground(Color.white);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtObservacaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtObservacaoFocusLost
        try {
            txtObservacao.setBackground(Color.white);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtObservacaoFocusLost

    private void btnFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFotoActionPerformed
        UtilVIEW.Imagem(lblFoto);
    }//GEN-LAST:event_btnFotoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        try {

            if (rbNovo.isSelected() == true) {

                if (txtNome.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Preencher o campo nome!",
                            "MENSAGEM", JOptionPane.WARNING_MESSAGE);
                    txtNome.requestFocusInWindow();
                } else {
                    CadastrarPessoaVIEW();

                }

            } else if (rbAlterar.isSelected() == true) {

                if (txtCodigo.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Pesquisar o " + tipo + "!",
                            "MENSAGEM", JOptionPane.WARNING_MESSAGE);
                } else {
                    if(lblFoto.getText().equals("")){
                        
                    }else{
                        AlterarImagemPessoa();
                    }
                    AlterarPessoaVIEW();
                    
                }

            }
            ConsultarPessoaVIEW("");
            UtilVIEW.LimparCampos(jPanel1);
            UtilVIEW.ImagemLabel("\\SolucaoSistemas\\src\\Imagem\\semFoto.jpg", lblFoto);
            txtNome.requestFocusInWindow();
        } catch (NullPointerException e) {
            System.out.println("" + e.getMessage());
        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        txtNome.requestFocusInWindow();
    }//GEN-LAST:event_formWindowOpened

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        try {
            if (PrincipalVIEW.cliente == true) {
                PrincipalVIEW.cliente = false;
            } else if (PrincipalVIEW.fornecedor == true) {
                PrincipalVIEW.fornecedor = false;
            } else if (PrincipalVIEW.veterinario == true) {
                PrincipalVIEW.veterinario = false;
            } else if (PrincipalVIEW.funcionario == true) {
                PrincipalVIEW.funcionario = false;
            } else if (PrincipalVIEW.empresa == true) {
                PrincipalVIEW.empresa = false;
            }
            this.dispose();
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btnSairActionPerformed

    private void txtNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyReleased

        ConsultarPessoaVIEW(txtNome.getText().toUpperCase());
    }//GEN-LAST:event_txtNomeKeyReleased

    private void tblPessoaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblPessoaKeyReleased
        CarregarJanela();
        ConsultarImagemPessoa();
    }//GEN-LAST:event_tblPessoaKeyReleased

    private void tblPessoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPessoaMouseClicked
        CarregarJanela();
        ConsultarImagemPessoa();
        rbAlterar.setSelected(true);
    }//GEN-LAST:event_tblPessoaMouseClicked

    private void rbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNovoActionPerformed
        UtilVIEW.LimparCampos(jPanel1);
        txtNome.requestFocusInWindow();
    }//GEN-LAST:event_rbNovoActionPerformed
    public static boolean clicaFoto = false;
    private void lblFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFotoMouseClicked
        clicaFoto = true;
        new FotoVIEW(null, true).setVisible(true);
    }//GEN-LAST:event_lblFotoMouseClicked

    private void lblFotoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFotoMouseEntered
        lblFoto.setToolTipText("Clique para ampliar!");
    }//GEN-LAST:event_lblFotoMouseEntered

    private void txtEnderecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEnderecoKeyPressed
        try {
            if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
                txtBairro.requestFocusInWindow();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtEnderecoKeyPressed

    private void txtBairroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBairroKeyPressed
        try {
            if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
                txtCidade.requestFocusInWindow();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtBairroKeyPressed

    private void txtCidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCidadeKeyPressed
        try {
            if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
                txtSigla.requestFocusInWindow();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtCidadeKeyPressed

    private void txtSiglaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSiglaKeyPressed
        try {
            if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
                txtObservacao.requestFocusInWindow();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtSiglaKeyPressed

    private void txtEnderecoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEnderecoFocusGained
        try {
            txtEndereco.setBackground(new Color(255, 255, 204));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtEnderecoFocusGained

    private void txtBairroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBairroFocusGained
        try {
            txtBairro.setBackground(new Color(255, 255, 204));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtBairroFocusGained

    private void txtCidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCidadeFocusGained
        try {
            txtCidade.setBackground(new Color(255, 255, 204));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtCidadeFocusGained

    private void txtSiglaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSiglaFocusGained
        try {
            txtSigla.setBackground(new Color(255, 255, 204));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtSiglaFocusGained

    private void txtEnderecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEnderecoFocusLost
        try {
            txtEndereco.setBackground(Color.white);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtEnderecoFocusLost

    private void txtBairroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBairroFocusLost
        try {
            txtBairro.setBackground(Color.white);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtBairroFocusLost

    private void txtCidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCidadeFocusLost
        try {
            txtCidade.setBackground(Color.white);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtCidadeFocusLost

    private void txtSiglaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSiglaFocusLost
        try {
            txtSigla.setBackground(Color.white);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtSiglaFocusLost

    public void CadastrarPessoaVIEW() {
        try {

            if (objpessoaCTR.CadastrarPessoaCTR(txtNome.getText().toUpperCase(),
                    txtApelido.getText().toUpperCase(),
                    txtCpf.getText(), txtRG.getText().toUpperCase(), txtNascimento.getText(),
                    txtTelefone1.getText(), txtTelefone2.getText(), txtCnpj.getText(),
                    txtFacebook.getText().toUpperCase(), txtInstagram.getText().toUpperCase(),
                    txtEmail.getText().toLowerCase(), "", "X", txtObservacao.getText().toUpperCase(),
                    tipo, lblFoto.getText(), txtEndereco.getText().toUpperCase(), txtBairro.getText().toUpperCase(),
                    txtCidade.getText().toUpperCase(), txtSigla.getText().toUpperCase())) {
                JOptionPane.showMessageDialog(null, "Salvo com sucesso!", "MENSAGEM",
                        JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Erro ao Salvar!", "MENSAGEM",
                    JOptionPane.WARNING_MESSAGE);
            System.out.println("Metodo" + e.getMessage());
        }
    }

    public void AlterarPessoaVIEW() {
        try {

            if (rbLiberado.isSelected() == true) {
                liberado = "X";
            } else if (rbLiberado.isSelected() == false) {
                liberado = "";
            }
            if (rbBloqueado.isSelected() == true) {
                bloqueado = "X";
            } else if (rbBloqueado.isSelected() == false) {
                bloqueado = "";
            }

            if (objpessoaCTR.AlterarPessoaCTR(txtNome.getText().toUpperCase(), txtApelido.getText().toUpperCase(),
                    txtCpf.getText(), txtRG.getText().toUpperCase(), txtNascimento.getText(),
                    txtTelefone1.getText(), txtTelefone2.getText(), txtCnpj.getText(),
                    txtFacebook.getText().toUpperCase(), txtInstagram.getText().toUpperCase(),
                    txtEmail.getText().toLowerCase(), bloqueado, liberado, txtObservacao.getText().toUpperCase(),
                    tipo, lblFoto.getText(), txtEndereco.getText().toUpperCase(), txtBairro.getText().toUpperCase(),
                    txtCidade.getText().toUpperCase(), txtSigla.getText().toUpperCase(), txtCodigo.getText())) {
                JOptionPane.showMessageDialog(null, "Atualizado com sucesso!", "MENSAGEM",
                        JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Erro ao Atualizar!", "MENSAGEM",
                    JOptionPane.WARNING_MESSAGE);
            System.out.println("" + e.getMessage());
        }
    }

    private void AlterarImagemPessoa(){
        try {
            objpessoaCTR.AlterarImagemPessoaCTR(lblFoto.getText(), txtCodigo.getText());
            System.out.println("Imagem Atualizada com sucesso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao AlterarImagemPessoa", 
                    "MENSAGEM", JOptionPane.WARNING_MESSAGE);
        }
    }
    private void ConsultarPessoaVIEW(String pesquisa) {
        try {

            pessoa = objpessoaCTR.ConsultarPessoaCTR("0", pesquisa, tipo, tipo);

            RestaurarPessoaVIEW(pessoa);
            pessoa = null;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao Consultar Pessoa",
                    "MENSAGEM", JOptionPane.WARNING_MESSAGE);

        }
    }

    private void ConsultarImagemPessoa(){
        try {
            ResultSet imagePessoa = null;
            imagePessoa = objpessoaCTR.ConsultarPessoaCTR(txtCodigo.getText(), "null", tipo, tipo);
            if(imagePessoa.next()){
                UtilVIEW.CarregaLabel(lblFoto, imagePessoa, "foto");
            }
            
        } catch (Exception e) {
            System.out.println("Erro ao ConsultarImagemPessoa "+e.getMessage());
        }
    }
    private void CarregarJanela() {
        try {
            txtCodigo.setText(tblPessoa.getValueAt(tblPessoa.getSelectedRow(), 0).toString());
            txtNome.setText(tblPessoa.getValueAt(tblPessoa.getSelectedRow(), 1).toString());
            txtApelido.setText(tblPessoa.getValueAt(tblPessoa.getSelectedRow(), 2).toString());
            if (tblPessoa.getValueAt(tblPessoa.getSelectedRow(), 5).toString().equals("   .   .   -  ")) {
                txtCpf.setText("");
            } else {
                txtCpf.setText(tblPessoa.getValueAt(tblPessoa.getSelectedRow(), 5).toString());
            }

            txtRG.setText(tblPessoa.getValueAt(tblPessoa.getSelectedRow(), 7).toString());
            if (tblPessoa.getValueAt(tblPessoa.getSelectedRow(), 15).toString().equals("  /  /    ")) {
                txtNascimento.setText("");
            } else {
                txtNascimento.setText(tblPessoa.getValueAt(tblPessoa.getSelectedRow(), 15).toString());
            }

            txtTelefone1.setText(tblPessoa.getValueAt(tblPessoa.getSelectedRow(), 3).toString());
            txtTelefone2.setText(tblPessoa.getValueAt(tblPessoa.getSelectedRow(), 4).toString());
            if (tblPessoa.getValueAt(tblPessoa.getSelectedRow(), 5).toString().equals("  .   .   /    -  ")) {
                txtCnpj.setText("");
            } else {
                txtCnpj.setText(tblPessoa.getValueAt(tblPessoa.getSelectedRow(), 6).toString());
            }

            txtFacebook.setText(String.valueOf(tblPessoa.getValueAt(tblPessoa.getSelectedRow(), 13)));
            txtInstagram.setText(String.valueOf(tblPessoa.getValueAt(tblPessoa.getSelectedRow(), 14)));
            txtEmail.setText(String.valueOf(tblPessoa.getValueAt(tblPessoa.getSelectedRow(), 12)));
            txtObservacao.setText(String.valueOf(tblPessoa.getValueAt(tblPessoa.getSelectedRow(), 16)));
            if (tblPessoa.getValueAt(tblPessoa.getSelectedRow(), 8).toString().equals("")) {
                txtEndereco.setText("");
            } else {
                txtEndereco.setText(String.valueOf(tblPessoa.getValueAt(tblPessoa.getSelectedRow(), 8)));
            }
            if (tblPessoa.getValueAt(tblPessoa.getSelectedRow(), 9).toString().equals("")) {
                txtBairro.setText("");
            } else {
                txtBairro.setText(String.valueOf(tblPessoa.getValueAt(tblPessoa.getSelectedRow(), 9)));
            }
            if (tblPessoa.getValueAt(tblPessoa.getSelectedRow(), 10).toString().equals("")) {
                txtCidade.setText("");
            } else {
                txtCidade.setText(String.valueOf(tblPessoa.getValueAt(tblPessoa.getSelectedRow(), 10)));
            }
            if (tblPessoa.getValueAt(tblPessoa.getSelectedRow(), 11).toString().equals("")) {
                txtSigla.setText("");
            } else {
                txtSigla.setText(String.valueOf(tblPessoa.getValueAt(tblPessoa.getSelectedRow(), 11)));
            }

            
        } catch (Exception e) {
            // JOptionPane.showMessageDialog(null, "Erro ao Carregar", "MENSAGEM", JOptionPane.WARNING_MESSAGE);
            rbAlterar.setSelected(true);
            System.out.println("" + e.getMessage());
        }
    }

    private void RestaurarPessoaVIEW(ResultSet rs) {
        try {
            DefaultTableModel dtm = (DefaultTableModel) tblPessoa.getModel();
            dtm.setRowCount(0);
            while (rs.next()) {
                dtm.addRow(new Object[]{rs.getString("codigo"), rs.getString("nome"),
                    rs.getString("apelido_nomefantasia"), rs.getString("telefone1"),
                    rs.getString("telefone2"), rs.getString("cpf"), rs.getString("cnpj"),
                    rs.getString("rg"), rs.getString("endereco"), rs.getString("bairro"),
                    rs.getString("cidade"), rs.getString("estado"), rs.getString("email"),
                    rs.getString("facebook"),
                    rs.getString("instagram"), rs.getString("data_nasc"),
                    rs.getString("observacoes"),
                    rs.getString("foto")});
            }
            tblPessoa.setModel(dtm);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao RestaurarPessoaVIEW",
                    "MENSAGEM", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PessoaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PessoaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PessoaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PessoaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                PessoaVIEW dialog = new PessoaVIEW(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFoto;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup grupoBloquear;
    private javax.swing.ButtonGroup grupoOpcoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblFoto;
    private javax.swing.JPanel pnlOpcoes;
    private javax.swing.JPanel pnlOperacao;
    private javax.swing.JRadioButton rbAlterar;
    private javax.swing.JRadioButton rbBloqueado;
    private javax.swing.JRadioButton rbLiberado;
    private javax.swing.JRadioButton rbNovo;
    private javax.swing.JTable tblPessoa;
    private javax.swing.JTextField txtApelido;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JFormattedTextField txtCnpj;
    public static javax.swing.JTextField txtCodigo;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtFacebook;
    private javax.swing.JTextField txtInstagram;
    private javax.swing.JFormattedTextField txtNascimento;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtObservacao;
    private javax.swing.JTextField txtRG;
    private javax.swing.JTextField txtSigla;
    private javax.swing.JTextField txtTelefone1;
    private javax.swing.JTextField txtTelefone2;
    // End of variables declaration//GEN-END:variables
}
